module.exports.user_Validation = require("./user.validation")
module.exports.product_Validation = require("./product.validation")
module.exports.cart_Validation = require("./cart.validation")
module.exports.order_Validation = require("./order.validation")
module.exports.category_Validation = require("./category.validation")